config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, length: { minimum: 3 }, uniqueness: true
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable,  :omniauth_providers => [:facebook]



   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
      #  user.name = auth.info.name   # assuming the user model has a name
      #  user.image = auth.info.image # assuming the user model has an image
       # If you are using confirmable and the provider(s) you use validate emails,
       # uncomment the line below to skip the confirmation emails.
       # user.skip_confirmation!
     end
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def restaurant_params
    params.require(:restaurant).permit(:name)
    # params.require(:restaurant).permit(:description)
    # params.require(:restaurant).permit(:id)
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
  @restaurant = Restaurant.new(restaurant_params)
  if @restaurant.save
    redirect_to restaurants_path
  else
    render 'new'
  end
end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    render template: "restaurants/new"
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create(review_params)

    redirect_to '/restaurants'
  end

  private

  def review_params
    params.require(:review).permit(:comments, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reji</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
    <div class="row">
      <div class="col-md-1">
        <%= image_tag("poison.jpg", size: "74x40", alt: "Reji", id: "logo") %>
        <!-- <img id="logo" src="/images/poison.jpg" width="74" height="40" /> -->
      </div>
      <div class="col-md-7">
        <h1><a href="/">Reji Restaurants</a></h1>
      </div>
      <div class="col-md-4">
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete,
          class: 'btn btn-default pull-right' %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path,
          class: 'btn btn-default pull-right'  %>
          <%= link_to "Sign up", new_user_registration_path,
          class: 'btn btn-default pull-right'  %>
        <% end %>
      </div>
    </div>
    <%if notice %>
      <div class="row">
        <p class="notice alert-info"><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="row">
        <p class="alert alert-warning"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
  </div> <!-- end container -->
  </body>
</html>

app/views/restaurants/edit.html.erb
<!-- <%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %> -->

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
    <div class="restaurant-links">
      <%= link_to "Edit Restaurant", edit_restaurant_path(restaurant) %> |
      <%= link_to "Delete Restaurant", restaurant_path(restaurant), method: :delete %> |
      <%= link_to "Add Review", new_restaurant_review_path(restaurant) %>
    </div>
    <ul>
    <% if restaurant.reviews.any? %>
      <% restaurant.reviews.each do |review| %>
        <li><div class="rating">Rating: <%= review.rating %></div><p><%= simple_format(review.comments) %></p></li>
      <% end %>
    <% end %>
    </ul>
  <% end %>
<% else %>
  No restaurants yet
<% end %>

<div class='row footer-button'>
  <%= link_to "Add a restaurant", new_restaurant_path, class: 'btn btn-default'%>
</div>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.description %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :comments %>
  <%= f.text_area :comments %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>